name: Build and Deploy Spring Boot to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build React frontend
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Copy frontend build to Spring Boot static resources
        run: |
          mkdir -p spring-boot-backend/src/main/resources/static
          cp -r frontend/build/* spring-boot-backend/src/main/resources/static/ || true

      - name: Build with Maven
        run: mvn -B clean package --file spring-boot-backend/pom.xml

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-backend
          path: spring-boot-backend/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-backend

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: CTS-VibeAppso3801-5
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: '*.jar'
