trigger:
  - main
 
pool:
  vmImage: ubuntu-latest
 
steps:
  # 1️⃣ Setup Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '22.x'
 
  # 2️⃣ Build frontend
  - script: |
      echo "=== Installing and building frontend ==="
      npm install --prefix frontend
      npm run build --prefix frontend
    displayName: 'Build Frontend'
 
  # 3️⃣ Create backend/public and copy build
  - script: |
      echo "=== Copying frontend build into backend/public ==="
      mkdir -p backend/public
      cp -r frontend/build/* backend/public/
    displayName: 'Prepare Backend Public Folder'
 
  # 4️⃣ Install backend dependencies
  - script: |
      echo "=== Installing backend dependencies ==="
      npm install --prefix backend
    displayName: 'Install Backend Dependencies'
 
  # 5️⃣ Archive backend for deployment
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'backend'
      includeRootFolder: false
      archiveType: zip
archiveFile: $(Build.ArtifactStagingDirectory)/app.zip
      replaceExistingArchive: true
 
  # 6️⃣ Deploy to Azure App Service
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'cb6255853a-vibecode03-az'
      appName: 'CTS-VibeAppso3801-5'
package: $(Build.ArtifactStagingDirectory)/app.zip