name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install and build frontend
        run: |
          echo "=== Installing and building frontend ==="
          npm install --prefix frontend
          npm run build --prefix frontend

      - name: Clean backend/public
        run: rm -rf backend/public/*

      - name: Copy frontend build to backend/public
        run: cp -r frontend/build/* backend/public/

      - name: Install backend dependencies
        run: |
          echo "=== Installing backend dependencies ==="
          npm install --prefix backend

      - name: Upload backend as artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: backend

      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-artifact
          path: downloaded-backend

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CTS-VibeAppso3801-5'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_36BA900ACACA403386F9C8DBBE9E58B8 }}
          package: ./backend
    